farm: add whitelisting addresses for farm endpoints
ElrondNetwork/sc-dex-rs pull request #221
Opened 2021-11-30 23:14 UTC by claudiulataretu

- Address whitelisting is used for farm accepting LKMEX as farming token
where proxy will be whitelisted in farm contract

Signed-off-by: Claudiu Ion Lataretu <claudiu.lataretu@gmail.com>

2021-12-01 07:10 UTC, sasurobert commented on dex/farm/src/lib.rs
> +        let caller = self.blockchain().get_caller();
you have to make one function out of lines 224-232. And use a require for it. one liner for this endpoint.

2021-12-01 07:10 UTC, sasurobert commented on dex/farm/src/lib.rs
> +        require!(apr_multiplier > 1, "farm does not support locked rewards");
I think that it is better to make a completely new set of contracts - one which generates locked rewards - thus metaESDTs and one which generates with ESDTs. That will make the overall contracts smaller.

2021-12-01 07:10 UTC, sasurobert commented on dex/farm/src/lib.rs
> +        let caller = self.blockchain().get_caller();
I would make a separate version for this contract. And would have especially for this case. You can start a new feat/branch - where you say farm with whitelist.

2021-12-02 10:33 UTC, catalinnnn requested changes
Looks good, but needs testing, we cannot keep adding changes without adding mandos tests

2021-12-13 07:41 UTC, closed without merging