Staking fixes
ElrondNetwork/sc-dex-rs pull request #306
Opened 2022-02-25 11:10 UTC by dorin-iancu

- APR limit applied globally instead of per user

2022-02-25 14:25 UTC, claudiulataretu requested changes

2022-02-25 14:54 UTC, sasurobert commented on dex/farm-staking/src/custom_rewards.rs
> +                self.get_amount_apr_bounded(&farm_token_supply);
+1

2022-02-25 15:02 UTC, sasurobert commented on dex/farm-staking/src/custom_rewards.rs
> +        _last_claim_block: u64,
This has to be deleted. It does not do what it says

2022-02-25 15:03 UTC, sasurobert commented on dex/farm-staking/src/custom_rewards.rs
> +                self.get_amount_apr_bounded(&farm_token_supply);
This is per block. So it should be ok

2022-02-25 15:04 UTC, sasurobert commented on dex/farm-staking/src/custom_rewards.rs
> +                self.get_amount_apr_bounded(&farm_token_supply);
Why don't we limit both local/user APR and global as well?

2022-02-25 15:04 UTC, sasurobert reviewed
Limit both local and global

2022-02-25 16:09 UTC, claudiulataretu approved these changes

2022-02-25 16:22 UTC, claudiulataretu commented on dex/farm-staking/src/custom_rewards.rs
> +                self.get_amount_apr_bounded(&farm_token_supply);
It works as it is. I had to double check for myself

2022-02-26 07:16 UTC, sasurobert approved these changes

2022-02-28 10:59 UTC, catalinnnn approved these changes

2022-02-28 11:04 UTC, merged

2022-02-28 11:06 UTC, claudiulataretu approved these changes