fix getUserEnergyForWeek
ElrondNetwork/sc-dex-rs pull request #486
Opened 2022-10-11 14:53 UTC by dragos-rebegea

2022-10-11 15:23 UTC, psorinionut submitted a review, later dismissed

2022-10-11 16:51 UTC, claudiulataretu requested changes

2022-10-11 16:51 UTC, claudiulataretu commented on energy-integration/common-modules/weekly-rewards-splitting/src/lib.rs
> +                week: 1,
I think it should be
` ClaimProgress {
                energy: current_user_energy,
                week: current_week,
            }`

2022-10-11 17:29 UTC, claudiulataretu approved these changes

2022-10-12 04:43 UTC, CostinCarabas approved these changes

2022-10-12 05:15 UTC, merged