simple lock exit farm fix
ElrondNetwork/sc-dex-rs pull request #684
Opened 2022-12-19 13:39 UTC by psorinionut

2022-12-19 13:50 UTC, dorin-iancu approved these changes

2022-12-19 21:41 UTC, sasurobert commented on locked-asset/simple-lock/src/proxy_farm.rs
> +                &exit_farm_result.remaining_farm_tokens.token_identifier,
shouldn't you send proxy token here ?

2022-12-20 07:32 UTC, dorin-iancu requested changes

2022-12-20 07:32 UTC, dorin-iancu commented on locked-asset/simple-lock/src/proxy_farm.rs
> +                exit_farm_result.remaining_farm_tokens.token_nonce,
```suggestion
                &payment.token_identifier,
                payment.token_nonce,
```

2022-12-20 08:29 UTC, psorinionut commented on locked-asset/simple-lock/src/proxy_farm.rs
> +                exit_farm_result.remaining_farm_tokens.token_nonce,
Updated.

2022-12-20 08:38 UTC, sasurobert approved these changes

2022-12-20 10:10 UTC, dorin-iancu approved these changes

2022-12-20 11:16 UTC, psorinionut commented on locked-asset/simple-lock/src/proxy_farm.rs
> +                &exit_farm_result.remaining_farm_tokens.token_identifier,
Updated.

2022-12-20 12:05 UTC, merged